name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1

    - name: Build webpack
      run: |
        npm install
        npm run-script build

    - name: Build web-ext
      uses: kewisch/action-web-ext@v1.0
      with:
        cmd: build
        source: dist
        verbose: true

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: beyond_campaigns-1.0.zip
        path: web-ext-artifacts/beyond_campaigns-1.0.zip

# https://github.com/marketplace/actions/publish-release