name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1

    - name: Build webpack
      run: |
        npm install
        npm run-script build

    - name: Build web-ext
      uses: kewisch/action-web-ext@v1.0
      with:
        cmd: build
        source: dist
        verbose: true

    - name: Create tag
      id: create_tag
      run: |
        version=$(cat version.txt)
        tag=builds-$(cat version.txt)
        echo "::set-output name=version::$version"
        echo "::set-output name=tag::$tag"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: beyond_campaigns-${{steps.create_tag.outputs.version}}.xpi
        path: web-ext-artifacts/beyond_campaigns-${{steps.create_tag.outputs.version}}.zip

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.version }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: web-ext-artifacts/beyond_campaigns-${{steps.create_tag.outputs.version}}.xpi
        asset_name: beyond_campaigns-${{steps.create_tag.outputs.version}}.xpi
        # asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}